### ISSUE TITLE
Getting false positives

### ISSUE THREAD

**Issue by fent** [ssivanatarajan/stylelint-group-selectors#4]
Some false positive scenarios I've noticed

- in scss, when nesting, blocks that have no immediate properties are considered to have the same properties

```scss
.a {
  .b {
    color: blue;
  }
}

.c { // <- will get a warning here saying it can be merged with `.a`
  .d {
    font-size:  12pt;
  }
}
```

- media queries are ignored

```css
@media (max-width: 100px) {
  .a {
    color: blue;
  }
}

@media (max-width: 200px) {
  .b { // <-- warning here saying it can be merged with `.a` above despite different @media query
    color: blue;
  }
}
```

- nesting in scss is ignored
```scss
.a {
  background: green;
  .b {
    color: red;
  }
}
.c { // <-- warning here saying it can be merged with `.b`
  color: red;
}
```
although the above warning is true, you may not always want to pull `.b` out of that block since `.a` could be a complicated selector that you may not want to repeat typing, and grouping `.b` inside `.a` can provide additional context.
